### ISSUE TITLE
User-defined operators can lead to insufficient fuel and constraint leakage

### ISSUE THREAD

**Issue by chengluyu** [hkust-taco/mlscript#180] opened 2023-09-20 11:36 UTC
The following is the preamble code used for reproduction.

```mls
:NewDefs

let anythingToString = toString
fun (++) stringConcat(a, b) = concat(a)(b)
//│ let anythingToString: anything -> Str
//│ fun (++) stringConcat: (Str, Str) -> Str
//│ anythingToString
//│                  = [Function: toString]

type List[A] = Cons[A] | Nil
class Cons[A](head: A, tail: List[A]) {
  fun join(sep: Str): Str
  fun join(sep) =
    if tail is
      Nil then toString(head)
      Cons(x, Nil) then toString(head) ++ sep ++ toString(x)
      Cons(x, xs) then toString(head) ++ sep ++ toString(x) ++ sep ++ xs.join(sep)
}
module Nil {
  fun join(sep: Str): Str = ""
  fun contains(x): Bool = false
}
//│ type List[A] = Cons[A] | Nil
//│ class Cons[A](head: A, tail: List[A]) {
//│   fun join: (sep: Str) -> Str
//│ }
//│ module Nil {
//│   fun contains: anything -> Bool
//│   fun join: (sep: Str) -> Str
//│ }

fun (::) cons[A](x: A, xs: List[A]): List[A] = Cons(x, xs)
//│ fun (::) cons: forall 'A. (x: 'A, xs: List['A]) -> List['A]

// (1 :: Nil).join(", ")
// (1 :: (2 :: Nil)).join(", ")
// (1 :: (2 :: (3 :: Nil))).join(", ")
// (1 :: (2 :: (3 :: (4 :: Nil)))).join(", ")

fun (:-) listExclude(xs, x) =
  if xs is
    Nil then Nil
    Cons(x', xs') and
      x === x' then xs' :- x
      else x' :: (xs' :- x)
//│ fun (:-) listExclude: forall 'A 'A0. (Cons['A] | Nil, Eql['A]) -> (Nil | List['A0])
//│   where
//│     'A <: 'A0
```

If you add the following code, it will cause the fuel to be used up. 

```mls
(1 :: Nil).join(", ")
(1 :: (2 :: Nil)).join(", ")
(1 :: (2 :: (3 :: Nil))).join(", ")
(1 :: (2 :: (3 :: (4 :: Nil)))).join(", ")
(1 :: (2 :: (3 :: (4 :: (5 :: Nil))))).join(", ")
//│ ╔══[ERROR] Subtyping constraint of the form `(x: ?A, xs: List[?A]) -> List[?A] <: (4, ?a) -> ?b` took too many steps and ran out of fuel (10000)
//│ ║  l.39: 	(1 :: (2 :: (3 :: (4 :: (5 :: Nil))))).join(", ")
//│ ║        	                   ^^^^^^^^^^^^^^^
//│ ╙── Note: use flag `:ex` to see internal error info.
//│ ╔══[ERROR] Subtyping constraint of the form `(x: ?A, xs: List[?A]) -> List[?A] <: (2, ?a) -> ?b` took too many steps and ran out of fuel (10000)
//│ ║  l.39: 	(1 :: (2 :: (3 :: (4 :: (5 :: Nil))))).join(", ")
//│ ║        	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//│ ╙── Note: use flag `:ex` to see internal error info.
//│ Str
//│ res
//│     = '1'
//│ res
//│     = '1, 2'
//│ res
//│     = '1, 2, 3'
//│ res
//│     = '1, 2, 3, 4'
//│ res
//│     = '1, 2, 3, 4, 5'
```

But if you add the following code, the latter test block will have a type error. Although the latter test block is type-correct when it appears on its own.

```mls
(Nil :- 0).join(", ")
((0 :: Nil) :- 0).join(", ")
((1 :: Nil) :- 0).join(", ")
((1 :: (2 :: Nil)) :- 0).join(", ")
//│ Str
//│ res
//│     = ''
//│ res
//│     = ''
//│ res
//│     = '1'
//│ res
//│     = '1, 2'

("x" :: Nil).join(", ")
//│ ╔══[ERROR] Type mismatch in operator application:
//│ ║  l.70: 	("x" :: Nil).join(", ")
//│ ║        	 ^^^^^^^^^^
//│ ╟── string literal of type `"x"` is not an instance of type `Num`
//│ ║  l.70: 	("x" :: Nil).join(", ")
//│ ║        	 ^^^
//│ ╟── Note: constraint arises from reference:
//│ ║  l.45: 	      x === x' then xs' :- x
//│ ║        	            ^^
//│ ╟── from field selection:
//│ ║  l.11: 	class Cons[A](head: A, tail: List[A]) {
//│ ║        	              ^^^^
//│ ╟── Note: method type parameter A is defined at:
//│ ║  l.32: 	fun (::) cons[A](x: A, xs: List[A]): List[A] = Cons(x, xs)
//│ ╙──      	              ^
//│ Str | error
//│ res
//│     = 'x'
```

Also, I noticed that the error message mentioned the type constraint from the `listExclude` function.

Moreover, if we don't use user-defined operators in the first test block, the typer will also consider the second block of code as correct.

**Comment by LPTK** [comment] 2023-09-20 12:54
Thanks for the report! Looks like the type of the operator is not properly generalized and is leaking. I figured it out by trying these things:

```scala
:stats
(1 :: Nil).join(", ")
//│ Str
//│ res
//│     = '1'
//│ constrain calls  : 37
//│ annoying  calls  : 8
//│ subtyping calls  : 162

cons
//│ forall 'A. (x: 'A, xs: List['A]) -> List['A]
//│   where
//│     'A :> 1
//│ res
//│     = [Function: cons]

:stats
(2 :: Nil).join(", ")
//│ Str
//│ res
//│     = '2'
//│ constrain calls  : 38
//│ annoying  calls  : 8
//│ subtyping calls  : 189

cons
//│ forall 'A. (x: 'A, xs: List['A]) -> List['A]
//│   where
//│     'A :> 1 | 2
//│ res
//│     = [Function: cons]
```

Notice how the same code takes more constraints when executed a second time, which is a telltale sign. Also see how the signature of `cons` changes.

I'll investigate the cause.

**Comment by LPTK** [comment] 2023-09-20 13:16
Fixed in https://github.com/hkust-taco/mlscript/commit/bce48deb7980edeb331b294a5f08251f814f846b!

What's nice is that this also resolved some issues in another test file that I had not yet had time to look into 😄

**Closed as completed by LPTK** 2023-09-20 13:16 UTC

**Comment by chengluyu** [comment] 2023-09-20 13:18
Fantastic!
