### ISSUE TITLE
Can access fields from `anything`?

### ISSUE THREAD

**Issue by Meowcolm024** [hkust-taco/mlscript#70] opened 2022-01-15 07:13 UTC
To reproduce, add tests with the following:
``` txt
res = if true then (1,2, "hello") else (true, 3)
res._1
//│ res: anything
//│    = [ 1, 2, 'hello' ]
//│ res: 1 | true
//│    = undefined
```
It is tested using the code in master branch.

**Comment by LPTK** [comment] 2022-01-15 08:12
Good catch! The problem is in the normal forms used to do type simplification. It shows `(1, 2, "hello",) | (true, 3,)` as equivalent to `anything`, but the real least upper bound here, at east according to the half-implemented semantics mentioned in https://github.com/hkust-taco/mlscript/issues/69, would be `{_1: 1 | true; _2: 2 | 3}`.

The specific problematic line is: https://github.com/hkust-taco/mlscript/blob/ffe4b380af32cb023a93310354d58f2f21cfc23e/shared/src/main/scala/mlscript/NormalForms.scala#L125

Pro-tip: here is how I debugged the issue:

```ts
:ns // show the unsimplified type (which is the one used in later checks)
res = if true then (1,2, "hello") else (true, 3)
//│ res: 'a | (1, 2, "hello",) | (true, 3,)
//│    = [ 1, 2, 'hello' ]

:d // show the constraining trace
res._1
//│ 0. Typing term res._1
//│ | 0. Typing term res
//│ | 0. : [α0]
//│ | CONSTRAIN [[α0]] <! {_1: α1}
//│ |   where α0 :> [(1<int,number>, 2<int,number>, "hello"<string>)] | [([true<bool>], 3<int,number>)]
//│ | C [[α0]] <! {_1: α1}
//│ | | C [α0] <! {_1: α1}
//│ | | | C α0 <! {_1: α1}
//│ | | | | C [(1<int,number>, 2<int,number>, "hello"<string>)] <! {_1: α1}
//│ | | | | | C (1<int,number>, 2<int,number>, "hello"<string>) <! {_1: α1}
//│ | | | | | | C {_1: 1<int,number>, _2: 2<int,number>, _3: "hello"<string>} <! {_1: α1}
//│ | | | | | | | C 1<int,number> <! α1
//│ | | | | C [([true<bool>], 3<int,number>)] <! {_1: α1}
//│ | | | | | C ([true<bool>], 3<int,number>) <! {_1: α1}
//│ | | | | | | C {_1: [true<bool>], _2: 3<int,number>} <! {_1: α1}
//│ | | | | | | | C [true<bool>] <! α1
//│ 0. : α1
//│ Typed as: α1
//│  where: α1 :> [true<bool>] | 1<int,number>
[...]
```

Here we can see that the result of the if-then-else is a type variable `α0` with two lower bounds, both of which are subtypes of the `{_1: α1}` upper bound required to type the field selection.

**Comment by LPTK** [comment] 2022-02-08 07:24
Fixed in https://github.com/hkust-taco/mlscript/pull/79

```scala
res = if true then (1,2, "hello") else (true, 3)
//│ res: Array["hello" | 1 | 2 | 3 | true] & {_1: 1 | true, _2: 2 | 3}

res._1
//│ res: 1 | true

res = if true then (1,2, "hello") else (true, 3)
res._3
//│ res: Array["hello" | 1 | 2 | 3 | true] & {_1: 1 | true, _2: 2 | 3}
//│ ╔══[ERROR] Type mismatch in field selection:
//│ ║  l.+2: 	res._3
//│ ║        	^^^^^^
//│ ╟── tuple literal of type `{_1: true, _2: 3}` does not have field '_3'
//│ ║  l.+1: 	res = if true then (1,2, "hello") else (true, 3)
//│ ║        	                                       ^^^^^^^^^
//│ ╟── but it flows into reference with expected type `{_3: ?a}`
//│ ║  l.+2: 	res._3
//│ ╙──      	^^^
//│ res: "hello" | error
```

**Closed as completed by LPTK** 2022-02-08 07:24 UTC
Labels: bug
